### ISSUE TITLE
Pass args to shellcheck

### ISSUE THREAD

**Issue by durkode** [buildkite-plugins/shellcheck-buildkite-plugin#11]
I would love to use this plugin, however what is blocking me is the inability to pass args to shellcheck, specifically rules to ignore and the -x option at the moment.

Would you welcome a PR for this? If so, are you happy with being able to pass through any options, or would you prefer to explicitly define what can be passed (such as rules to ignore)?

**Comment by lox** [comment]
We'd happily accept a PR with args to pass, or rules specifically if it works better. 

We tend to put our ignored rules inline in source comments, so haven't needed it yet!

**Comment by durkode** [comment]
Opened https://github.com/buildkite-plugins/shellcheck-buildkite-plugin/pull/12 to address this.

**Comment by lox** [comment]
Closed in #12.
