### ISSUE TITLE
Plugin does not support docker image pinning

### ISSUE THREAD

**Issue by rpdillon** [buildkite-plugins/shellcheck-buildkite-plugin#30]
Looking for timely merge of #29, since I think some (all?) users of this plugin are experiencing breakage since the official docker image's `latest` build is broken.  See https://github.com/koalaman/shellcheck/issues/1751 for more details.

**Comment by TigerWolf** [comment]
Would also love this.

**Comment by toote** [comment]
PR #29 has already been merged so closing this one
