### ISSUE TITLE
show building this plugin code supposed to work out the box?

### ISSUE THREAD

**Issue by sas94086** [buildkite-plugins/shellcheck-buildkite-plugin#33]
Im getting errors in all my tests. 
spellcheck, lint, tests etc.

Here's an example error from spellcheck:

Running global environment hook | 0s
-- | --
  | Setting up elastic stack environment (v4.4.0) | 0s
  | Downloading secrets from  buildkiteec2stack-1-managedsecretsbucket-ojcfogfb902s | 6s
  | Preparing plugins | 0s
  | Preparing working directory | 1s
  | Running global pre-command hook | 0s
  | Running plugin shellcheck command hook | 0s
  | $ /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-shellcheck-buildkite-plugin-v1-1-2/hooks/command
  | No files found to shellcheck
  | 🚨 Error: The command exited with status 1
  | Running global pre-exit hook | 0s
  | $ /etc/buildkite-agent/hooks/pre-exit

Im new to Buildkite and is using this to test

**Comment by toote** [comment]
Hi @sas94086, sorry for the long delay in getting back to you. From the looks of it the issue is that whatever value you set as the `files` for this plugin (if any) did not match any files in your repository and pipeline, and when that happens the plugin will fail just as you have seen.
